#!/usr/bin/env python3
"""Generate the textbook figures from ``cmbcore`` output (WP4).

Each figure is written to ``figures/`` and registered in
``figures/manifest.yaml`` (figure id -> filename). This script produces the
core spectrum/background/recombination figures; the full ~60-figure set is the
WP4 deliverable and extends this module.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from cmbcore import Params, BackgroundCosmology, Recombination, PowerSpectrum
from cmbcore import constants as const
from cmbcore.plotstyle import use_style
from cmbcore.io import load_cls

OUT = Path(__file__).resolve().parent.parent / "figures"
OUT.mkdir(exist_ok=True)
MANIFEST = OUT / "manifest.yaml"


def _save(fig, fid, fname, manifest):
    path = OUT / fname
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    manifest[fid] = fname
    print(f"  {fid}: {fname}")


def fig_background(p, bg, manifest):
    x = np.linspace(-15, 0, 400)
    fig, ax = plt.subplots()
    Om = bg.Omega(x)
    for key, lbl in [("gamma", r"$\gamma$"), ("nu", r"$\nu$"),
                     ("b", "b"), ("c", "c"), ("Lambda", r"$\Lambda$")]:
        ax.plot(x, Om[key], label=lbl)
    ax.axvline(np.log(1 / (1 + bg.z_eq())), ls="--", c="k", lw=1,
               label=r"$z_{\rm eq}$")
    ax.set_xlabel(r"$x=\ln a$")
    ax.set_ylabel(r"$\Omega_i(x)$")
    ax.set_title("Background density fractions")
    ax.legend(ncol=3)
    _save(fig, "F2.1", "bg_density_fractions.png", manifest)


def fig_recombination(p, bg, rec, manifest):
    x = np.linspace(-9, -5, 600)
    z = np.exp(-x) - 1
    fig, ax = plt.subplots()
    ax.semilogy(z, rec.Xe(x))
    ax.axvline(rec.z_star(), ls="--", c="r", lw=1,
               label=fr"$z_*={rec.z_star():.0f}$")
    ax.set_xlabel("redshift $z$")
    ax.set_ylabel(r"$X_e(z)$")
    ax.set_title("Free-electron fraction (Saha + Peebles)")
    ax.invert_xaxis()
    ax.legend()
    _save(fig, "F2.2", "recomb_Xe.png", manifest)

    fig, ax = plt.subplots()
    ax.plot(x, rec.g_tilde(x), label=r"$\tilde g(x)$")
    ax2 = ax.twinx()
    ax2.semilogy(x, rec.tau(x), c="C1", label=r"$\tau(x)$")
    ax.set_xlabel(r"$x=\ln a$")
    ax.set_ylabel(r"visibility $\tilde g$")
    ax2.set_ylabel(r"$\tau$")
    ax.set_title("Optical depth and visibility function")
    _save(fig, "F2.3", "recomb_visibility.png", manifest)


def fig_spectrum(manifest):
    cache = OUT / "cls_fiducial.npz"
    if not cache.exists():
        print("  (run scripts/make_values.py first for cls_fiducial.npz)")
        return
    d = load_cls(cache)
    ells, Dl = d["ells"], d["cls"]  # cache stores D_ell under the 'cls' key
    fig, ax = plt.subplots()
    ax.plot(ells, Dl)
    ax.set_xlabel(r"multipole $\ell$")
    ax.set_ylabel(r"$D_\ell=\ell(\ell+1)C_\ell\,T_{CMB}^2/2\pi\ \ [\mu K^2]$")
    ax.set_title(r"CMB temperature power spectrum $D_\ell^{TT}$")
    ax.set_xlim(2, ells.max())
    _save(fig, "F11.1", "cl_tt_fiducial.png", manifest)


def main():
    use_style()
    p = Params.fiducial()
    bg = BackgroundCosmology(p)
    rec = Recombination(bg, p)
    manifest = {}
    print("Generating figures:")
    fig_background(p, bg, manifest)
    fig_recombination(p, bg, rec, manifest)
    fig_spectrum(manifest)

    lines = ["# figure id -> filename (auto-generated by make_figures.py)"]
    for fid in sorted(manifest):
        lines.append(f"{fid}: {manifest[fid]}")
    MANIFEST.write_text("\n".join(lines) + "\n")
    print(f"Wrote {MANIFEST}")


if __name__ == "__main__":
    main()
